---
- name: "Mirroring image to multiple locations"
  block:
    - name: "Setting list list of mirrors"
      no_log: true
      set_fact:
        mi_mirrors: "{{ mirror_index_images.split(',') }}"

    - name: "Loop over all mirror locations"
      no_log: true
      include_tasks: mirror_single.yml
      loop: "{{ mi_mirrors }}"
      loop_control:
        loop_var: mi
  tags:
    - mirror_index
    - deploy_bundles
