---
- name: "Get info about supported cluster for {{ dov_op_name }} {{ doic_versions_processing }} from {{ labels_file_path }}"
  shell: "{{ yq_bin_path }} r {{ labels_file_path }} -t annotations.[com.redhat.openshift.versions]"
  register: ocp_version_annotation
  ignore_errors: true
  when:
    - annotations_file_path_presence.stat.exists
    - not ptq_ready|bool

- name: "Set parsed versions"
  when:
    - ocp_version_annotation is defined
    - ocp_version_annotation.stdout is defined
    - ocp_version_annotation.stdout!='null'
    - ocp_version_annotation.stdout|length > 0
    - annotations_file_path_presence.stat.exists
  set_fact:
    ocp_version_annotation_stdout: "{{ ocp_version_annotation.stdout }}"
    ptq_ready: false

- name: "Annotation file exists with no entry about OCP version"
  when:
    - ocp_version_annotation is defined
    - ocp_version_annotation.stdout is defined
    - ocp_version_annotation.stdout=='null'
    - annotations_file_path_presence.stat.exists
  set_fact:
    ptq_ready: true
