- name: "Getting sha from operator bundle version '{{ sis_registry_namespace }}/{{ item }}'"
  shell: "skopeo inspect docker://{{ sis_registry_namespace }}/{{ item }}"
  register: bs_skopeo_inspect

- name: "Reseting bs_skopeo_inspect_info"
  set_fact:
    bs_skopeo_inspect_info: {}

- name: "Settin bs_skopeo_inspect_info"
  set_fact:
    bs_skopeo_inspect_info: "{{ bs_skopeo_inspect.stdout | from_json }}"
  when: bs_skopeo_inspect.rc == 0

- name: "Adding sha as version for {{ sis_registry_namespace }}/{{ item }} "
  set_fact:
    bob_bundles_sha_arr: "{{ bob_bundles_sha_arr | default([]) }} + [ '{{ sis_registry_namespace }}/{{ operator_package_name }}@{{ bs_skopeo_inspect_info.Digest }}' ]"
  when: 
    - bs_skopeo_inspect_info.Digest is defined
    - bs_skopeo_inspect_info.Digest != ""

