---

- debug:
    var: si_item

- name: "Export ci.yaml info"
  include_role:
    name: export_ci_yaml
  vars:
    ecy_path: "{{ catalog_repo_dir }}/{{ op_base_name }}/{{ si_item }}/ci.yaml"

- name: "Build operator '{{ si_item }}' from '{{ sis_index_image }}'' to sha index"
  include_role:
    name: build_operator_index_sha
  vars:
    sis_index_image_input: "{{ sis_index_image }}"
    sis_package_name: "{{ si_item }}"
    opm_index_add_mode: "{{ ci_yaml_vars.updateGraph | replace('-mode','') }}"
    sis_export_skip: true
    sis_index_rm_skip: true


