---

- name: "Seting scorecards select variables"
  set_fact:
    bundle_scorecard_test_select_args: ""

- name: "Seting scorecards variables by default setup"
  set_fact:
    bundle_scorecard_test_config: "{{ work_dir }}/scorecard_config.yml"
    bundle_scorecard_test_select_args: "-l 'test in (basic-check-spec-test)'"
  when:
    - (bundle_scorecard_test_config is undefined or bundle_scorecard_test_config|length == 0)
    - (bundle_scorecard_test_select is undefined or bundle_scorecard_test_select|length == 0)

- name: "Process the scorecard config template"
  template:
    src: "scorecard_config.yml.j2"
    dest: "{{ work_dir }}/scorecard_config.yml"

- name: "Seting scorecards variables by select '{{ bundle_scorecard_test_select_args }}'"
  set_fact:
    bundle_scorecard_test_select_args: "-l 'test in ({{ bundle_scorecard_test_select }})'"
  when:
    - bundle_scorecard_test_select is defined
    - bundle_scorecard_test_select|length > 0

- name: "Run operator-sdk scorecard tests on the deployed operator in json form"
  shell: "{{ operator_sdk_bin_path }} alpha scorecard {{ bundle_image }} -c {{ bundle_scorecard_test_config }} {{ bundle_scorecard_test_select_args }}"
  failed_when: false
  register: bundle_scorecard_result

- name: "Print score card results"
  debug:
    var: bundle_scorecard_result.stdout

- name: "Failing when bundle scorecard test failed"
  fail:
    msg: "Bundle scorecard test failed for bundle image {{ bundle_image }} !!!"
  when: bundle_scorecard_result.rc != 0
