---
- name: "Docker installaion on ubuntu"
  block:
    - name: "Update apt cache"
      apt: update_cache=yes cache_valid_time=3600

    - name: Upgrade all apt packages
      apt: upgrade=dist

    - name: Install dependencies
      apt:
        name: "{{ packages }}"
        state: present
        update_cache: true
      vars:
        packages:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - gnupg-agent

    - name: Add an apt signing key for Docker
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add apt repository for stable version
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
        state: present

    - name: Install Docker
      apt:
        name: "{{ packages }}"
        state: present
        update_cache: true
      vars:
        packages:
          - docker-ce
          - docker-ce-cli 
          - containerd.io
  become: true
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  tags:
    - install
    - host_build

- name: "Docker installaion on redhat"
  block:
    - name: Add Docker CE repository
      shell: yum-config-manager --add-repo=https://download.docker.com/linux/centos/docker-ce.repo
      args:
        creates: /etc/yum.repos.d/docker-ce.repo

    - name: "Install docker-ce"
      yum:
        name: docker-ce
        state: present
  become: true
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux' or ansible_distribution == 'Fedora'
  tags:
    - install
    - host_build

- name: "Ensure group docker exists"
  group:
    name: "{{ docker_group }}"
    state: present
  become: true
  tags:
    - install
    - host_build

- name: "Add ansible user to docker group"
  user:
    name: "{{ docker_user }}"
    groups: docker
    append: true
  become: true
  tags:
    - install
    - host_build

- name: reset ssh connection
  meta: reset_connection
  tags:
    - install
    - host_build

- name: "Ensure docker service started"
  service:
    name: docker
    state: started
  become: true
  tags:
    - install
    - host_build
